// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYtJ-NMY5aBN9NFAvOxdgiboEszKfOqsM',
    appId: '1:434865111249:web:6ff85d2e83d5886940c5f0',
    messagingSenderId: '434865111249',
    projectId: 'cashe-register-11a3b',
    authDomain: 'cashe-register-11a3b.firebaseapp.com',
    storageBucket: 'cashe-register-11a3b.appspot.com',
    measurementId: 'G-YEHG5CMR2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwADZpEggm8n7iOsRPDwveGLmudsXGH7A',
    appId: '1:434865111249:android:3532f73a33b2257440c5f0',
    messagingSenderId: '434865111249',
    projectId: 'cashe-register-11a3b',
    storageBucket: 'cashe-register-11a3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3eLG3STw0WXqrqsnlNdIVMyBE48VJWCE',
    appId: '1:434865111249:ios:4d8ce727064d8beb40c5f0',
    messagingSenderId: '434865111249',
    projectId: 'cashe-register-11a3b',
    storageBucket: 'cashe-register-11a3b.appspot.com',
    iosClientId: '434865111249-sogoda91pci2um9hoq8qjankurif2ovp.apps.googleusercontent.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3eLG3STw0WXqrqsnlNdIVMyBE48VJWCE',
    appId: '1:434865111249:ios:afb62f8c0502d29940c5f0',
    messagingSenderId: '434865111249',
    projectId: 'cashe-register-11a3b',
    storageBucket: 'cashe-register-11a3b.appspot.com',
    iosClientId: '434865111249-7e0jvia4t46ok6l1b2e1g8u0chd4ui4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.application.RunnerTests',
  );
}
